### ISSUE TITLE
dbus-broker timeouts during system startup

### ISSUE THREAD

**Issue by mskarbek** [bus1/dbus-broker#121]
On minimal Fedora 28 Server installation with package from `updates-testing` repo (`dbus-broker-13-1.fc28.x86_64`), `dbus-broker` timeouts during system startup by waiting for NSS to resolve UID of `gdm` which in minimal installation is not present.
```
May 07 02:07:31 node01 systemd[1]: Starting D-Bus System Message Bus...
May 07 02:07:31 node01 dbus-broker-launch[406]: Looking up UID for user 'gdm' over NSS...
May 07 02:09:01 node01 systemd[1]: dbus-broker.service: Start operation timed out. Terminating.
May 07 02:10:31 node01 systemd[1]: dbus-broker.service: State 'stop-sigterm' timed out. Killing.
May 07 02:10:31 node01 systemd[1]: dbus-broker.service: Killing process 406 (dbus-broker-lau) with signal SIGKILL.
May 07 02:10:31 node01 systemd[1]: dbus-broker.service: Failed with result 'timeout'.
May 07 02:10:31 node01 systemd[1]: Failed to start D-Bus System Message Bus.
May 07 02:10:31 node01 systemd[1]: dbus-broker.service: Consumed 13ms CPU time
```

**Comment by dvdhrm** [comment]
Yeah, this is a known issue. The new nss-systemd module (available since F28) is buggy. Doesn't matter whether you run dbus-daemon or dbus-broker. Only difference is dbus-broker makes it easier to trigger since we have that gdm-special-casing.

Details here: https://bugzilla.redhat.com/show_bug.cgi?id=1565735

Possible workarounds:

 * disable selinux (or put into permissive mode)
 * install gdm (just to make sure the 'gdm' user exists)
 * use dbus-daemon for now

I will leave this open for some days, in case other people hit this. We are working with systemd people on a proper fix.

**Comment by mskarbek** [comment]
Ok, thanks for the info and bug link. I've switched back to  dbus-daemon for now, disabling selinux is not an option.

**Comment by teg** [comment]
This was fixed upstream in the SELinux policy.
