### ISSUE TITLE
selinux code looks broken again

### ISSUE THREAD

**Issue by doverride** [bus1/dbus-broker#164]
```
Aug 03 20:30:50 julius dbus-broker[1119]: A security policy denied :1.219 to send method call /org/freedesktop/DBus:org.freedesktop.DBus.Hello to org.freedesktop.DBus.
Aug 03 20:30:50 julius audit[1119]: USER_AVC pid=1119 uid=81 auid=4294967295 ses=4294967295 subj=sys.id:sys.role:dbus.system.subj:s0 msg='Unknown class dbus exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?'
Aug 03 20:30:50 julius audit[1119]: USER_AVC pid=1119 uid=81 auid=4294967295 ses=4294967295 subj=sys.id:sys.role:dbus.system.subj:s0 msg='avc:  received policyload notice (seqno=2)
                                     exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?'
```
dbus-broker-14-3.fc29.x86_64

**Comment by doverride** [comment]
Actually this bug issue is not new. I downgraded to 1.11 and it is there as well...

**Comment by doverride** [comment]
I dont know of a better way to explain this issue: https://www.youtube.com/watch?v=cLr_ao_wvC0

**Comment by teg** [comment]
What do you mean 1.11? Version of what? dbus-broker?

Do you have any custom SELinux rules at all? I'm not able to reproduce this I'm afraid.

**Comment by doverride** [comment]
On Wed, Aug 08, 2018 at 04:00:01AM -0700, Tom Gundersen wrote:

I mean 11

> What do you mean 1.11? Version of what? dbus-broker?
> 
> Do you have any custom SELinux rules at all? I'm not able to reproduce this I'm afraid.

Yes I am using custom policy but that is not relevant since it does not work in permissive mode either.

This seems to only happen with a session instance of dbus-broker, and not the system instance.

If you cannot reproduce then I suppose for now close it. If it is an issue in Fedora then it will (re) surface eventually.

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bus1/dbus-broker/issues/164#issuecomment-411367981

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
I cannot consistently reproduce this currently. If i am able to get more info then I will re-open this

**Comment by doverride** [comment]
On Wed, Aug 08, 2018 at 04:00:01AM -0700, Tom Gundersen wrote:
> What do you mean 1.11? Version of what? dbus-broker?
> 
> Do you have any custom SELinux rules at all? I'm not able to reproduce this I'm afraid.

Might be related to atspi. atspi starts its own session dbus (it doesnt use dbus-broker)

I "killed -HUP" the main atspi-bus-launcher process and things started to work. As a bonus it seems gtk apps arent trying to start atspi anymore after i killed it the first time....

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bus1/dbus-broker/issues/164#issuecomment-411367981

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
Looks like at_spi2 added some dbus-broker support in Rawhide.

It is not working though:

```
Aug 26 11:57:22 julius systemd[1259]: at-spi-dbus-bus.service: Failed with result 'exit-code'.
Aug 26 11:57:22 julius systemd[1259]: at-spi-dbus-bus.service: Main process exited, code=exited, status=1/FAILURE
Aug 26 11:57:22 julius at-spi-bus-launcher[18150]: Failed to launch bus: Bus exited with code 1
Aug 26 11:57:22 julius at-spi-bus-launcher[18150]: /usr/bin/dbus-broker-launch: unrecognized option '--verbose'
Aug 26 11:57:22 julius systemd[1259]: Started Accessibility services bus.

**Comment by Keruspe** [comment]
That's not related to selinux at all, and should be fixed by https://github.com/bus1/dbus-broker/pull/166

**Comment by doverride** [comment]
Thanks, yes I know that is not directly related to SELinux. It is indirectly related to this issue though (even though i wont be able to test it until this commit lands in Rawhide)

**Comment by teg** [comment]
Thanks for the report, fix pushed to rawhide!

**Comment by dvdhrm** [comment]
> Yes this fixes it. Looks like this also addresses the SELinux issue. Although i suppose not the fundamental issue of having a dbus-broker as well as a dbus session bus running at the same time. Granted that shouldnt happen, but still

The dbus specification defines generic "buses", and this is what is implemented by `dbus-daemon` and `dbus-broker`. Anyone on the system can fork and execute these processes to run their own private bus (and every project is welcome to do so, if the general purpose buses do not serve their needs).

The general purpose buses are just 2 kinds of predefined buses. They are not in any way special other than that they are defined as part of the specification. at-spi2 does for historical reason run its own private bus. This is because dbus-daemon couldn't handle the huge load of messages that can happen at times on at-spi2, so people decided to pull it off the session bus. Whether or not this still applies today is open for discussion. We designed dbus-broker in a way that this should no longer be necessary, but so far nobody tried merging the bus back.

> Also the at-spi2 stuff is pretty ugly in general
> basically atspi bus launcher listens on a unix domain socket, that dbus-broker then accepts connections on. in turn at_spi clients and flatpak dbusproxy then unix stream socket connectto it.

To my knowledge the at-spi2 bus is in no way special, but works just like other buses (eg., the session bus).

> also seems that atspi regd is started with a runtime unit? Would have been prettier if that at-spi bus was socket activated and if regd would have a unit file in /usr/lib/system/user/at-spi2-regd.service or something....

Again, I am no authority on at-spi2, so not sure whether this is still how it works: I think at-spi2 provides a service on the *session bus* which can be queried to get the bus-address of the at-spi2 private bus. This services is very likely bus-activated, and thus the at-spi2 bus should only start once the first service queries the bus address.
Since no-one can "guess" the private bus address, this should be working fine.
