### ISSUE TITLE
Allow for references instead of global identifiers

### ISSUE THREAD

**Issue by bl33pbl0p** [bus1/dbus-broker#173]
This is a feature request or a extension to the protocol, feel free to close it if it breaks backward compatibility.

I was wondering if D-Bus as it is could allow clients to instead grab a reference to some object, and then grant privileges to anyone who uses that reference to make bus calls, the same as the one who obtained it (think of file descriptors). I guess this needs more refinement and some thought on how to implement it, but say passing back an integer as a return value and the server storing permissions granted for that integer whenever used as a refernce in bus calls when making method calls/modifying properties.

This allows for two neat things:

* Clients can pass around these references to something else over a trust boundry and grant privileges to them without involving policykit (which is problematic for non-interactive uses).
* Clients can do privilege separation after setting up a reference they want to use for their lifecycle, drop them completely, or things like systemd and flatpak could pass mock interfaces to do sandboxing for clients. Flatpak could instead let clients use those mock references to the interface instead of filtering messages over its dbus-proxy that has a great performance impact.

I'm interested in elaborating futher if this is something that developers are interested in implemening in some acceptable form. One could also allow schemes where closing that reference from the original client means revoking access for other users. This also allows one to do some sort of namespacing in D-Bus.

**Comment by dvdhrm** [comment]
The keyword here is `capability-based security` (which is a bit misleading due to the name-collision with POSIX/Linux Capabilities).

Yes, introducing such object/handle style communication is definitely something we want. The `bus1` project is our kernel-based transport that introduces this concept as a top-level communication primitive, similar in style to other modern IPCs (See Google-Binder, BSD-Mach, Google-Mojo, etc.)

We did talk a lot about introducing this feature to D-Bus. Something similar to FD-Passing, where you have a handle-array in your message header, that contains all the object-handles you pass with the message, and then dbus-daemon will track the handles you have access to.

We still work on the next evolution of the bus1 kernel module. If that materializes, I think it would make such a dbus extension obsolete. That's a big "if", though.

**Comment by bl33pbl0p** [comment]
Ah, great. I wasn't sure if bus1 was still in the works (no commits recently) hence the issue ticket here.

Since that has been brought up, I was curious if bus1 \*can\* also be used to expose kernel resources as objects on the bus and userspace may treat them as capabilities (since I remember kdbus being discussed as a potential replacement for the kobject-uevent netlink socket, hence there is some credence to this idea) since that makes a lot of sense if we're slowly wanting to turn Linux into a true capability based system.

**Comment by bl33pbl0p** [comment]
Ah, great. I wasn't sure if bus1 was still in the works (no commits recently) hence the issue ticket here.

Since that has been brought up, I was curious if bus1 \*can\* also be used to expose kernel resources as objects on the bus and userspace may treat them as capabilities (since I remember kdbus being discussed as a potential replacement for the kobject-uevent netlink socket, hence there is some credence to this idea) since that makes a lot of sense if we're gradualy wanting to turn Linux into a true capability based system.

**Comment by dvdhrm** [comment]
> Ah, great. I wasn't sure if bus1 was still in the works (no commits recently) hence the issue ticket here.

Still in the works!
 
> Since that has been brought up, I was curious if bus1 *can* also be used to expose kernel resources as objects on the bus and userspace may treat them as capabilities (since I remember kdbus being discussed as a potential replacement for the kobject-uevent netlink socket, hence there is some credence to this idea) since that makes a lot of sense if we're gradualy wanting to turn Linux into a true capability based system.

Yes, I made sure that `bus1` can be used from in-kernel threads as well. However, I do question its applicability. If it is about performance, hand-crafted syscalls will never be beaten by IPC (at least I don't see that happening). On the other hand, if it is not about performance, you can always write a user-space wrapper-service that exposes your kernel-objects through IPC. Especially for existing kernel APIs, this is probably the argument people will bring forward.

I do agree that there are APIs like netlink that would benefit from a fresher look. But you have to keep in mind that kernel APIs are long lived and people tend to stick to what exists.

Having said that, I would love to see bus1 being used to expose kernel-internal state as well. We can always keep dreaming!

**Comment by dvdhrm** [comment]
I will close this, since I do not intend to work on this. I highly recommend leaving DBus to its existing use-cases, and instead employing capability-base IPC to get said features.

If anyone is interested in working on this, feel free to re-open this! However, from our side there is no intention to work on this, sorry.
