### ISSUE TITLE
unnecessarily disconnecting clients

### ISSUE THREAD

**Issue by mvduin** [bus1/dbus-broker#192]
dbus-broker, similar to the original dbus-daemon, currently has as policy to disconnect peers if any problem is found with the encoding of a message. While this is obviously necessary if message_new_incoming fails (MESSAGE_E_CORRUPT_HEADER or MESSAGE_E_TOO_LARGE), it is pointlessly harsh to do so at any later time.

Besides being very uninformative, being disconnected from the message bus may be very difficult to recover from, especially since the client does not know the fate of outstanding calls or other recently sent messages. Forcing the client to perform strict validation of all outgoing messages pointlessly duplicates work that the message bus will do again, and is a waste of cpu time. There is also always a risk that the validation done by reimplementations does not precisely match that of the message bus (either by mistake or because it is viewed as cumbersome), e.g.:

    ~$ busctl call org.freedesktop.systemd1 / x.y z $(yes v | head -n 65) i 42
    Connection reset by peer

My suggestion would be to
- send an error to the sender, at least if the malformed message is a method call with reply expected, and preferably for method calls and signals in general
- send an error to the destination if the malformed message is a method reply or error message (to ensure the caller doesn't wait for a reply that will never come)
- drop the erroneous message and move on

**Comment by dvdhrm** [comment]
The reason for the current behavior is that we mimic what `dbus-daemon` does. We try to minimize the observable deviations from `dbus-daemon`, which is also why we try to explicitly document all of them in the [wiki](https://github.com/bus1/dbus-broker/wiki/Deviations/). So the easiest way to get this changed, is to change it in `dbus-daemon`.

Anyway, having said that, we don't mind deviating if that improves on usability, performance, etc. and there is definitely a point in telling clients why they were disconnected. @teg worked on that quite a bit, and we try to send error messages to clients with the exact reason why they were disconnected. There is definitely room for improvement, though. Note that D-Bus allows error-replies to **any** message, so this is not limited to method-calls (you need to be careful not to trigger a recursion, though).

Regarding your request not to disconnect clients, I am not so enthusiastic about. Can you elaborate why you would want this? What is a concrete scenario where it would be beneficial to continue after a marshaling error?
To elaborate on this: The broker has no idea how important the malformed message was. Furthermore, it might have been a message-reply or a signal, which the sender does not expect to fail. A caller does not expect replies to those. By dropping such messages, we paper over bugs where we have no clue how wide-reaching they might be. By forcefully disconnecting the client, we use our strongest tool available to reject any responsibility on hiding possibly security relevant bugs in an application.

So I would appreciate a bit more context. Where do you see this happening? Why would a client be required to validate messages? In what situation would a client ever send malformed messages?

As a last note: I would like to never have to validate messages in the broker. This way the broker would be freed of any responsibility. However, for several reasons (matching, eavesdropping, compatibility, ...) the broker has to look at message content, and thus forwarding malformed messages is not an option. We are left with the choice of dropping the message and continue, or disconnect. We chose the latter because we have seen many situations where dropping messages introduces lingering bugs that trigger much later than the actual malformed message was sent.

**Comment by dvdhrm** [comment]
Just some more information on this, so it is not forgotten:

@teg investigated this some time ago. The reason `dbus-daemon` does not send an error before closing a connection is because their protocol library calls `close(2)` immediately when a connection is torn down. That is, the outgoing queue is **not** flushed to the client, but rather dropped immediately. They have no way to keep it in a lingering state until the outgoing messages are sent. It would require a significant rework of `libdbus`.

This is **not** an issue in `dbus-broker`. We support unidirectional shutdowns. Meaning, you can close the two directions of a stream independently, keeping the other unaffected. We use this on misbehaving clients and only close the incoming direction of the client. We will thus no longer read any messages from it, but we keep flushing the pending queue to the client. Once the outgoing queue is empty, we close the outgoing side as well.

Hence, it should be rather straightforward to make `dbus-broker` amend the needed information whenever it rejects a client.

**Comment by dvdhrm** [comment]
I am closing this as there seems to be no update on this.
