### ISSUE TITLE
Bluetooth Mouse on GDM does not work at all, while perfectly works for all logged-in users

### ISSUE THREAD

**Issue by Tids** [bus1/dbus-broker#199]
With dbus-broker, while on GDM it looks like Bluetooth does not work at all. I cant see something to connect my mouse. Once logged in, I can use the mouse just normal.
With dbus, it will also work on GDM.

It does not look like there is anything about this in the logs, or I'm just unable to find it.

**Comment by dvdhrm** [comment]
What distribution are you on? Or did you build dbus-broker yourself?

**Comment by dvdhrm** [comment]
To elaborate on this: you very likely want to pass `-Dsystem-console-users=gdm` to `meson` when configuring it.

The underlying issue here is BlueZ making use of the deprecated `at-console` policy selector. This feature is not supported by dbus-broker in the same way dbus-daemon supported it, since there is no way to implement it correctly without sacrificing performance.

Luckily, BlueZ upstream already stopped using `at-console`, but we are still waiting for a release. As a workaround, you can pass `-Dsystem-console-users=gdm` to meson to tell dbus-broker that the listed user(s) are considered `at-console`.

**Comment by Tids** [comment]
Ahh OK! Thanks. I'll give feedback later today. :)

**Comment by Taijian** [comment]
I tried this and it seems to work. (On Arch with GDM/Gnome DE)

**Comment by Tids** [comment]
@dvdhrm It's Arch and this really seems to work. Thanks!
So (hopefully) with the next BlueZ-release this will be fixed?

**Comment by Tids** [comment]
@Taijian https://bugs.archlinux.org/task/62308?project=1&string=dbus-broker thanks for this :+1:

**Comment by dvdhrm** [comment]
I was about to drop a message to Jan Steffens to update the package... I now replied on the bug-tracker instead. Thanks for testing this and reporting to Arch upstream!

FYI: I am about to update `dbus-broker-git` in the AUR as well.

If there are no further issues, I will close this report. Thanks a lot!

**Comment by Maryse47** [comment]
> With dbus-broker we decided to not implement this broken logic. Instead, every user ID higher than SYSTEMUIDMAX (defined by systemd, and usually evaluates to `999`) is considered `at-console`. The `system-console-users` meson-configuration-option allows to provide further UIDs that should be considered `at-console`.

Does it mean `nobody` user us always considered `at-console`? And all dynamic users from systemd? Is that safe approach?

**Comment by dvdhrm** [comment]
> Does it mean `nobody` user is always considered `at-console`? And all dynamic users from systemd? Is that safe approach?

"yes", "yes", and "I assume so".

Longer story:

`at-console` was never really safe. It is cached indefinitely, and is also sourced from passwd, rather than from a live source. As such, the guarantee it grants boils down to `there was once a process of this user that was considered 'at-console' at connect-time, so we now may consider (under given circumstances) any further process of a matching UID 'at-console'`.
The feature has long been deprecated in upstream dbus. With dbus-broker we decided to go a step further and only map it to non-system-users. Furthermore, we sent patches to all remaining projects that still use 'at-console'.
Lastly, note that all remaining users should still be perfectly safe even with 'at-console' being completely ignored. If that is not the case, please let us know and we will look into it.

Cheers!
David

**Comment by Maryse47** [comment]
Isn't the next step to treat all UID > 0 users at console then? That will solve issues with greeters without need for downstream actions for distros.

**Comment by dvdhrm** [comment]
@Maryse47 Yes, that is an option we considered. It would definitely make things simpler, both for users and for us. The downside is that we would have no infrastructure to reinstate the old behavior at runtime, in the case we missed a valid use-case for `at-console`.
We chose an option that can reasonable well be implemented without any runtime performance penalties, but still close enough to the original behavior that it carries value.

In the long run, we definitely want to get rid of `at-console`. I think we want to wait for Fedora-30 to be released, though, and focus on the ongoing transition from dbus-daemon to dbus-broker there. If that goes all well, we should consider moving forward.

Anyway, discussion on `at-console` is definitely welcome! And opinions in favor of dropping it are always nice to read. If a longer discussion is wanted, I would suggest opening a separate issue, though, not to mix it with bug-reports here.

Thanks
David

**Comment by teg** [comment]
This is a useful discussion, but the reported problem appears solved, so I'm going to go ahead and close this. Feel free to reopen this if the problem exists, or to create a new issue if anyone has more to contribute to the at_console discussion.
