### ISSUE TITLE
Run dbus-broker on non-systemd system

### ISSUE THREAD

**Issue by protonesso** [bus1/dbus-broker#204]
Hi! I'm interested in your project! I've built system without systemd, because I use musl libc. I've disabled dbus-broker-launch because it requires systemd. I use openrc as my init system and I made service for dbus-broker but "dbus-broker --system" didn't work, I also tried to type "dbus-broker" but it didn't work too. I typed "dbus-broker --help" but it didn't give any help. Can I use dbus-broker-launch with elogind? Do you want to support non-systemd systems?

**Comment by teg** [comment]
Hi! Thanks for your interest! dbus-broker-launch is the integration of dbus-broker with systemd. If you want to use dbus-broker as your system bus without systemd you'd need an alternative launcher. I'm not aware of anyone working on alternative implementations, I'm afraid.

**Comment by protonesso** [comment]
can you write dbus-broker-launch for non-systemd systems?

**Comment by teg** [comment]
Yes, that's certainly possibly, if someone is willing to do the work.

**Comment by teg** [comment]
Closing, as this is outside the scope of dbus-broker.

**Comment by protonesso** [comment]
@teg how can I make launcher for it? Any documentation about broker?

**Comment by teg** [comment]
Please see the dbus-broker man page.

**Comment by protonesso** [comment]
@teg also, it is possible to make a launcher using dbus api?

**Comment by protonesso** [comment]
and what's file-descriptor controller

**Comment by teg** [comment]
Yes, that's possible. I recommend looking at how dbus-broker-launcher is implemented for a sample.

**Comment by protonesso** [comment]
Can you write info about --controller argument?

2019年12月29日(日) 21:04 Tom Gundersen <notifications@github.com>:

**Comment by dvdhrm** [comment]
> Can you write info about --controller argument?

Please ask more specifically about what is unclear. The `dbus-broker(1)` man-page contains information on the API of the controller. The `dbus-broker-launch` implementation is quite minimal and a good start to see how the API can be used. If you are stuck, please clearly tell us what is unclear so we can answer open question and improve the documentation.

**Comment by stalkerg** [comment]
@teg Will be good to reopen this issue but not as bug but as future enhancement. 
Also can you write a little what kind of integration exist here https://github.com/bus1/dbus-broker/blob/main/src/launch/launcher.c (I mean concept)?
Dbus-daemon perfectly work without systemd and I don't understand why it's needed for the default luncher for dbus-broker.

Because this projects describet as
> The dbus-broker project is an implementation of a message bus as defined by the D-Bus specification

I suppose it shouldn't be lock in on systemd.  If you develp it exclusive for systemd you should change next phrase:
> It is exclusively written for Linux systems
to
> It is exclusively written for Linux/systemd systems

but in same time I hope it was just first goal.

**Comment by stalkerg** [comment]
Ok, I found some explanations here: https://wiki.gentoo.org/wiki/Hard_dependencies_on_systemd

**Comment by teg** [comment]
Hi @stalkerg,
Conceptually, the launcher integrates the bus with the system. The main integration point is to use the init system to spawn daemons, as mentioned at the bottom of the list from the Gentoo wiki. The default launcher integrates with the systemd init system, and if you wish to use an alternate init implementation you could write an alternate launcher for that. That is, however, not something we are interested in working on or maintaining (and apparently neither is anyone else as nobody wrote any code), which is why this issue was closed.

I don't think it makes sense to highlight the dependence on systemd in the way you suggest. The broker is closely tied to linux APIs (unlike dbus daemon), but it is init-system agnostic. The fact that the default launcher requires systemd is covered in the wiki.

**Comment by stalkerg** [comment]
> I don't think it makes sense to highlight the dependence on systemd in the way you suggest. The broker is closely tied to linux APIs (unlike dbus daemon), but it is init-system agnostic. The fact that the default launcher requires systemd is covered in the wiki.

ok, got it

> That is, however, not something we are interested in working on or maintaining (and apparently neither is anyone else as nobody wrote any code), which is why this issue was closed.

as you can see some people very close looking into the code as me as well. I suppose nobody written new code jsut because before was not clear benefits from dbus-broker if dbus-dameon exist. Currently, it's much more interesting. 

> The main integration point is to use the init system to spawn daemons, as mentioned at the bottom of the list from the Gentoo wiki.

but if it's not needed? (OpenRC working diffrently here) Looks like we can just remove half of luncher and it will work.

**Comment by teg** [comment]
> but if it's not needed? (OpenRC working diffrently here) Looks like we can just remove half of luncher and it will work. 

When a name is is activated you'll need to spawn the corresponding daemon yourself if you do not integrate with an init system, you'll also need to keep track of the environment variables to pass. That shouldn't be too hard, just wanted to point out that you'll likely need to add more code, not only remove stuff.

If you end up writing a new launcher, do let us know if any of the api documentation is unclear.
