### ISSUE TITLE
Several Errors from dbus-broker-launch on linux boot | org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'

### ISSUE THREAD

**Issue by rsramkis** [bus1/dbus-broker#339]
On boot, the system journals are reporting the following errors and warnings from dbus-broker-launch:

- org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'
- Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.kde.dolphin.FileManager1.service'
- Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored

**Section of the Journal boot logs:**
```
Jan 22 11:54:17 mani systemd[842]: Starting D-Bus User Message Bus...
Jan 22 11:54:17 mani systemd[1]: eos-reboot-required.service: Deactivated successfully.
Jan 22 11:54:17 mani dbus-broker-launch[908]: Service file '/usr/share//dbus-1/services/org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'.
Jan 22 11:54:17 mani dbus-broker-launch[908]: Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.kde.dolphin.FileManager1.service'
Jan 22 11:54:17 mani dbus-broker-launch[908]: Service file '/usr/share//dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
Jan 22 11:54:17 mani dbus-broker-launch[908]: Service file '/usr/share//dbus-1/services/org.kde.plasma.Notifications.service' is not named after the D-Bus name 'org.freedesktop.Notifications'.
Jan 22 11:54:17 mani dbus-broker-launch[908]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Jan 22 11:54:17 mani dbus-broker-launch[908]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Jan 22 11:54:17 mani systemd[842]: Started D-Bus User Message Bus.
Jan 22 11:54:17 mani dbus-broker-launch[908]: Ready
```

**System:**
Kernel: 6.6.13-1-lts 
arch: x86_64 bits: 64 
Distro: EndeavourOS
dbus-broker version: 35

**Forum Post:**
https://forum.endeavouros.com/t/dbus-broker-new-boot-messages-after-the-past-month-updates/50178

**Comment by dvdhrm** [comment]
Hi! Can you elaborate where exactly you need help? Thanks!

**Comment by dvdhrm** [comment]
> > Hi! Can you elaborate where exactly you need help? Thanks!
> 
> Hi,
> 
> I'm looking for feedback on why dbusbroker is reporting the messages I have highlighted from the logs. These are relatively new messages I see everytime I cold boot my computer:

Sure! I can elaborate on each message, in case it is not clear.

>     * org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'

Dolphin apparently ships a D-Bus service file which uses a name different than the bus-name it claims. This is deprecated by the D-Bus reference implementation and even forbidden on the system bus. The Dolphin developers are urged to change this configuration.

>     * Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.kde.dolphin.FileManager1.service'

You apparently have multiple services installed which claim the name `org.freedesktop.FileManager1`, thus `dbus-broker` has to decide which one to use. It chose to ignore the Dolphin one. You can find other services files in the same directory.

>     * Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored

`Eavesdrop` is a D-Bus feature that was superseded by `monitors`. `dbus-broker` does not implemented eavesdropping, but your D-Bus configuration file still enables it. This message tells you that eavesdropping-configurations will be ignored.

This is likely because your distribution ships the dbus configuration file from the reference implementation. This still contains eavesdrop configurations, even though the feature has not been used for many years.

**Comment by rsramkis** [comment]
Thank you for your feedback.

I believe the reason we are seeing the error related to Dolphin is because I have both Dolphin an Nautilus (Gnome) on my system for testing. So I can ignore this error.

The 'eavesdropping' message on the other hand looks like I should dig a bit. Arch Linux recently made "[dbus-broker-units](https://archlinux.org/packages/core/x86_64/dbus-broker-units/)" its default.  

Any recommendation what file I should be looking at which contains the dbus configuration(as well as what setting I should be looking for related to the deprecated easdropping settings?

**Comment by dvdhrm** [comment]
> Thank you for your feedback.
> 
> I believe the reason we are seeing the error related to Dolphin is because I have both Dolphin an Nautilus (Gnome) on my system for testing. So I can ignore this error.

Yes, this sounds likely.

I think the better setup for these tools would be to have a generic dbus service for `org.freedesktop.FileManager1` which activates systemd `dbus-org.freedesktop.FileManager1.service`, which then itself is an alias for the correct systemd-service file of the currently activated file-manager. But I guess this is something for them to decide and figure out.

> The 'eavesdropping' message on the other hand looks like I should dig a bit. Arch Linux recently made "[dbus-broker-units](https://archlinux.org/packages/core/x86_64/dbus-broker-units/)" its default.
> 
> Any recommendation what file I should be looking at which contains the dbus configuration(as well as what setting I should be looking for related to the deprecated easdropping settings?

On ArchLinux `systemd` pulls in `dbus` (the reference implementation). This provides its default bus configuration in `/usr/share/dbus-1/`. The `dbus-broker` package re-uses this configuration on ArchLinux, since no alternative configuration is provided.

There is nothing in particular you should do about this. This setup works fine. I personally think the reference-implementation should update the default configuration to no longer mention `eavesdrop`, so we can gradually stop supporting it. But no-one has done that for now, so you are seeing the warnings in the log.

**Comment by rsramkis** [comment]
Thanks for your feedback (definitely a start in my reading to better understand systemd and dbus-broker). I did read through the system.conf file and as you said there is not really an issue here (just warning messages). It seems if someone at Arch Linux decides to make changes to the confirguration it will come from them or recommendations upstream.

It was a pleasure. Closing this issue as complete and answerd.
